target_sources(rbplus PRIVATE
    AnalysisNetwork.m
    AnalysisNetworkCore.m
    AppDelegate.mm
    ApplilinkBundle.m
    ApplilinkConsts.m
    ApplilinkCore.m
    ApplilinkDebug.m
    ApplilinkIndicator.m
    ApplilinkMessage.m
    ApplilinkNetwork.m
    ApplilinkNetworkError.m
    ApplilinkParameters.m
    ApplilinkPasteBoard.m
    ApplilinkStore.m
    ApplilinkURLConnection.m
    ApplilinkUdid.m
    ApplilinkUtilities.m
    ApplilinkViewController.m
    ApplilinkWebAPI.m
    AudioManager.mm
    BFCodec.m
    BannerView.m
    Crypto.m
    DestinationCore.m
    DownloadResourceManager.m
    Downloader.m
    GraphCircleView.m
    GraphView.m
    History.m
    HistoryData.m
    ImageDownloader.m
    MusicData.m
    MusicDataExtend.m
    MusicDataFromDoc.m
    NSArray+RB.m
    NSData+RB.m
    NSFileManager+RB.m
    NSString+RB.m
    NSStringURLEncoding.m
    NetworkUtil.m
    PagingScrollView.m
    PurchaseTransactionCache.m
    RBAnimationFactory.m
    RBApplilinkView.m
    RBBGMManager.m
    RBBaseTabBarController.mm
    RBBaseTableViewController.mm
    RBBaseViewController.mm
    RBBonusData.m
    RBCampaignData.m
    RBCampaignDetailViewController.m
    RBCampaignViewController.m
    RBCharacterBase.m
    RBCollectionView.m
    RBCoreDataManager.m
    RBCorporateViewController.m
    RBCreditsView.m
    RBCustomInfoPopupView.mm
    RBCustomSelectCollectionCell.m
    RBCustomSelectCollectionView.mm
    RBCustomSelectView.mm
    RBCustomView.mm
    RBErosionMarkUpdater.m
    RBErosionMarkUpdaterAlertController.m
    RBErosionMarkUpdaterScoreView.m
    RBExperienceData.mm
    RBExtendNoteManager.m
    RBGameKitManager.m
    RBHowToView.m
    RBHttpUtil.m
    RBManageSortData.m
    RBMapAnnotation.m
    RBMenuBGEffectPartView.mm
    RBMenuBGEffectView.mm
    RBMenuButton.m
    RBMenuMascot.mm
    RBMenuNewsTickerView.m
    RBMenuPageSlider.m
    RBMenuPageSliderView.m
    RBMenuTutorialView.mm
    RBMenuView.mm
    RBMusicCell.m
    RBMusicGridLayout.m
    RBMusicManager.m
    RBMusicMenuPopupView.mm
    RBNavigationController.m
    RBNewsHUDView.m
    RBNotificationData.m
    RBNotificationPagePhoneViewController.mm
    RBNotificationPageView.m
    RBNumberLabel.m
    RBPastelManager.m
    RBPlaylistCreateViewController.m
    RBPlaylistManager.m
    RBPlaylistViewController.m
    RBPopoverBackgroundView.m
    RBPopupView.mm
    RBPurchaseManager.mm
    RBPushNotificationView.mm
    RBRankingTableCell.m
    RBRankingTableView.m
    RBRankingView.mm
    RBResourceDownloadBGEffectPartView.m
    RBResourceDownloadViewController.m
    RBResoureDownloadBGEffectView.m
    RBRewardListView.m
    RBSearchMapView.m
    RBSearchMapViewController.mm
    RBSearchView.m
    RBServerAPIManager.m
    RBSettingMenuButton.m
    RBSettingView.mm
    RBStoreDetailViewController.m
    RBStoreExtendNoteDetailViewController.m
    RBStoreExtendNoteList.m
    RBStoreExtendPageViewController.mm
    RBStoreGenreViewController.m
    RBStoreManageCell.m
    RBStoreManageHeaderCell.m
    RBStoreManageSortViewController.m
    RBStoreManageViewController.m
    RBStorePackList.m
    RBStorePageViewController.m
    RBStoreTabController.mm
    RBTermAgreeView.mm
    RBTermDetailPhoneViewController.m
    RBTermPhoneViewController.mm
    RBTermView.m
    RBThemaView.mm
    RBTutorialManager.m
    RBTutorialPastel.m
    RBTutorialPastelLayer.m
    RBUnlockCollectionCell.m
    RBUnlockCollectionView.m
    RBUnlockData.m
    RBUnlockPackageData.m
    RBUnlockPackageItemData.m
    RBUnlockView.mm
    RBUrlSchemeInfoController.m
    RBUrlSchemeManager.m
    RBUrlSchemeStoreController.m
    RBUserSettingData.m
    RBViewController.mm
    RBWebView.m
    RecommendAdAreaView.m
    RecommendAdCache.m
    RecommendAdData.m
    RecommendAdId.m
    RecommendAdWebView.m
    RecommendCore.m
    RecommendDebug.m
    RecommendFullScreenController.m
    RecommendNetwork.m
    RecommendWebAPI.m
    RecommendWebView.m
    RecommendWebViewController.m
    ReplayData.m
    ReplayNote.m
    RewardCore.m
    RewardNetwork.m
    RewardWebAPI.m
    RewardWebViewController.m
    RotateStoreProductViewController.m
    SFSafariViewController+RB.m
    SKStoreProductViewController+RB.m
    ScoreData.m
    ScoreTracker.cpp
    SePlayer.m
    ShadeView.m
    SoundData.m
    SoundManager.m
    SoundPlayer.m
    StoreButtonView.m
    StoreCampaignDetailViewPad.m
    StoreCampaignItemInfo.m
    StoreCampaignTableViewCell.m
    StoreDetailCopyrightCell.m
    StoreDetailHeaderView.m
    StoreDetailMusicCell.m
    StoreDialogView.m
    StoreDownloadManager.m
    StoreDownloadTask.m
    StoreExtendNoteCell.m
    StoreExtendNoteCellPhone.m
    StoreExtendNoteView.m
    StoreExtendNoteDetailViewPad.m
    StoreExtendNoteInfo.m
    StoreExtendNoteInfoDownloader.m
    StoreImageView.m
    StoreMusicInfo.m
    StorePackCell.m
    StorePackDetailViewPad.m
    StorePackInfo.m
    StorePackInfoDownloader.m
    StorePackListGenre.m
    StorePackMusicView.m
    StorePackView.m
    StorePromotionTableCell.m
    StorePromotionView.m
    StoreTableCell.m
    StoreTableCellBase.m
    StoreTableCellViewBase.m
    StoreUtil.m
    StringConvert.m
    SystemHardware.m
    TwitterImageCreater.mm
    TwitterImageCreaterScoreElement.m
    UIAlertView+RB.m
    UIColor+RB.m
    UIImage+RB.m
    UIImageView+RB.m
    UITextView+RB.m
    UIView+RB.m
    main.m
    neGLView.mm
    neWindow.m
    tutorial_clip_rect_table.cpp
    AnalysisNetwork.h
    AnalysisNetworkCore.h
    AppDelegate.h
    ApplilinkBundle.h
    ApplilinkConsts.h
    ApplilinkCore.h
    ApplilinkDebug.h
    ApplilinkIndicator.h
    ApplilinkMessage.h
    ApplilinkNetwork.h
    ApplilinkNetworkError.h
    ApplilinkParameters.h
    ApplilinkPasteBoard.h
    ApplilinkStore.h
    ApplilinkURLConnection.h
    ApplilinkUdid.h
    ApplilinkUtilities.h
    ApplilinkViewController.h
    ApplilinkWebAPI.h
    AudioManager.h
    BFCodec.h
    BannerView.h
    Crypto.h
    DestinationCore.h
    DownloadResourceManager.h
    Downloader.h
    GraphCircleView.h
    GraphView.h
    History.h
    HistoryData.h
    ImageDownloader.h
    MusicData.h
    MusicDataExtend.h
    MusicDataFromDoc.h
    NSArray+RB.h
    NSData+RB.h
    NSFileManager+RB.h
    NSString+RB.h
    NSStringURLEncoding.h
    NetworkUtil.h
    PagingScrollView.h
    PurchaseTransactionCache.h
    RBAnimationFactory.h
    RBApplilinkView.h
    RBBGMManager.h
    RBBaseTabBarController.h
    RBBaseTableViewController.h
    RBBaseViewController.h
    RBBonusData.h
    RBCampaignData.h
    RBCampaignDetailViewController.h
    RBCampaignViewController.h
    RBCharacterBase.h
    RBCollectionView.h
    RBCoreDataManager.h
    RBCorporateViewController.h
    RBCreditsView.h
    RBCustomInfoPopupView.h
    RBCustomSelectCollectionCell.h
    RBCustomSelectCollectionView.h
    RBCustomSelectView.h
    RBCustomView.h
    RBErosionMarkUpdater.h
    RBErosionMarkUpdaterAlertController.h
    RBErosionMarkUpdaterScoreView.h
    RBExperienceData.h
    RBExtendNoteManager.h
    RBGameKitManager.h
    RBHowToView.h
    RBHttpUtil.h
    RBMacros.h
    RBManageSortData.h
    RBMapAnnotation.h
    RBMenuBGEffectPartView.h
    RBMenuBGEffectView.h
    RBMenuButton.h
    RBMenuMascot.h
    RBMenuNewsTickerView.h
    RBMenuPageSlider.h
    RBMenuPageSliderView.h
    RBMenuTutorialView.h
    RBMenuView.h
    RBMusicCell.h
    RBMusicGridLayout.h
    RBMusicManager.h
    RBMusicMenuPopupView.h
    RBNavigationController.h
    RBNewsHUDView.h
    RBNotificationData.h
    RBNotificationPagePhoneViewController.h
    RBNotificationPageView.h
    RBNumberLabel.h
    RBPastelManager.h
    RBPlaylistCreateViewController.h
    RBPlaylistManager.h
    RBPlaylistViewController.h
    RBPopoverBackgroundView.h
    RBPopupView.h
    RBPurchaseManager.h
    RBPushNotificationView.h
    RBRankingTableCell.h
    RBRankingTableView.h
    RBRankingView.h
    RBResourceDownloadBGEffectPartView.h
    RBResourceDownloadViewController.h
    RBResoureDownloadBGEffectView.h
    RBRewardListView.h
    RBScoreHash.h
    RBSearchMapView.h
    RBSearchMapViewController.h
    RBSearchView.h
    RBServerAPIManager.h
    RBSettingMenuButton.h
    RBSettingView.h
    RBStoreDetailViewController.h
    RBStoreExtendNoteDetailViewController.h
    RBStoreExtendNoteList.h
    RBStoreExtendPageViewController.h
    RBStoreGenreViewController.h
    RBStoreManageCell.h
    RBStoreManageHeaderCell.h
    RBStoreManageSortViewController.h
    RBStoreManageViewController.h
    RBStorePackList.h
    RBStorePageViewController.h
    RBStoreTabController.h
    RBTermAgreeView.h
    RBTermDetailPhoneViewController.h
    RBTermPhoneViewController.h
    RBTermView.h
    RBThemaView.h
    RBTutorialManager.h
    RBTutorialPastel.h
    RBTutorialPastelLayer.h
    RBUnlockCollectionCell.h
    RBUnlockCollectionView.h
    RBUnlockData.h
    RBUnlockPackageData.h
    RBUnlockPackageItemData.h
    RBUnlockView.h
    RBUrlSchemeControllerProtocol.h
    RBUrlSchemeInfoController.h
    RBUrlSchemeManager.h
    RBUrlSchemeStoreController.h
    RBUserSettingData.h
    RBViewController.h
    RBWebView.h
    RecommendAdAreaView.h
    RecommendAdCache.h
    RecommendAdData.h
    RecommendAdId.h
    RecommendAdWebView.h
    RecommendCore.h
    RecommendDebug.h
    RecommendFullScreenController.h
    RecommendNetwork.h
    RecommendWebAPI.h
    RecommendWebView.h
    RecommendWebViewController.h
    ReplayData.h
    ReplayNote.h
    RewardCore.h
    RewardNetwork.h
    RewardWebAPI.h
    RewardWebViewController.h
    RotateStoreProductViewController.h
    SFSafariViewController+RB.h
    SKStoreProductViewController+RB.h
    ScoreData.h
    ScoreTracker.h
    SePlayer.h
    ShadeView.h
    SoundData.h
    SoundManager.h
    SoundPlayer.h
    StoreButtonView.h
    StoreCampaignDetailViewPad.h
    StoreCampaignItemInfo.h
    StoreCampaignTableViewCell.h
    StoreDetailCopyrightCell.h
    StoreDetailHeaderView.h
    StoreDetailMusicCell.h
    StoreDialogView.h
    StoreDownloadManager.h
    StoreDownloadTask.h
    StoreExtendNoteCell.h
    StoreExtendNoteCellPhone.h
    StoreExtendNoteView.h
    StoreExtendNoteDetailViewPad.h
    StoreExtendNoteInfo.h
    StoreExtendNoteInfoDownloader.h
    StoreImageView.h
    StoreMusicInfo.h
    StorePackCell.h
    StorePackDetailViewPad.h
    StorePackInfo.h
    StorePackInfoDownloader.h
    StorePackListDelegate.h
    StorePackListGenre.h
    StorePackMusicView.h
    StorePackView.h
    StorePromotionTableCell.h
    StorePromotionView.h
    StoreTableCell.h
    StoreTableCellBase.h
    StoreTableCellViewBase.h
    StoreUtil.h
    StringConvert.h
    SystemHardware.h
    TwitterImageCreater.h
    TwitterImageCreaterScoreElement.h
    UIAlertView+RB.h
    UIColor+RB.h
    UIImage+RB.h
    UIImageView+RB.h
    UITextView+RB.h
    UIView+RB.h
    neGLView.h
    neWindow.h
)

target_include_directories(rbplus PRIVATE .)

add_subdirectory(GameSystem)
add_subdirectory(OpenGL)
add_subdirectory(Util)
add_subdirectory(Views)
