#!/usr/bin/env python3
"""
Build a name-to-address symbol map for the original binary from the reconstruction's annotations.

The shipped binary is stripped, so lldb shows its functions as ___lldb_unnamed_symbol1377 and a
backtrace says nothing. Every routine this tree has reconstructed carries an ``@ghidraAddress``
naming the address it came from, which is exactly the mapping that is missing -- roughly nineteen
hundred functions of it.

Reading the original's runtime values is what found the last defect, after repeated readings of its
code had each come back faithful, so making that easier is worth the tool. Without it, every
breakpoint costs an image-list, a hex addition and a paste; with it, the address is a lookup.

    tools/gen_symbol_map.py                     # offset  name, sorted by offset
    tools/gen_symbol_map.py --load 0x100990000  # absolute addresses for a running process
    tools/gen_symbol_map.py --load 0x100990000 --lldb > syms.lldb
                                                # a sourceable file of `breakpoint set -a` aliases

The load address is the first column of `image list -h -o -f "REFLEC BEAT plus"`. It changes every
launch, so regenerate rather than keeping the absolute form around.

Only definitions are collected: an annotation in a header describes a declaration, and the same
address annotated in both places would otherwise appear twice.
"""

import argparse
import re
import sys
from pathlib import Path

# `/** @ghidraAddress 0x2f638 */` or `// @ghidraAddress 0x2f638`, then the definition it documents.
_ANNOTATION = re.compile(r'@ghidraAddress\s+(0x[0-9a-f]+)')

# The name in a definition line: `void ne::C_SPRITE_INSTANCING_2D::Render() {`,
# `static void tempAssert(bool b) {`, `- (void)Draw {`, `RBMusicView *view = ...`.
# The trailing name is anchored on a word boundary so a qualified name is not clipped: without it
# the lazy prefix eats the first character of `C_SPRITE_INSTANCING_2D::~C_SPRITE_INSTANCING_2D`.
_CXX_DEFINITION = re.compile(
    r'^[A-Za-z_][\w:<>,*&\s]*?\b(~?[A-Za-z_]\w*(?:::~?[A-Za-z_]\w*)*)\s*\([^;]*$')
_OBJC_METHOD = re.compile(r'^[-+]\s*\([^)]*\)\s*(\w+)')

_SOURCES = ('.mm', '.cpp', '.m', '.c')


def symbols(root):
    """Every annotated definition, as {address: name}. Later files do not overwrite earlier ones."""
    found = {}
    for path in sorted(root.rglob('*')):
        if path.suffix not in _SOURCES:
            continue
        try:
            lines = path.read_text(encoding='utf-8').splitlines()
        except (OSError, UnicodeDecodeError):
            continue
        for index, line in enumerate(lines):
            match = _ANNOTATION.search(line)
            if not match:
                continue
            # Walk forward past the rest of the comment block to the definition it documents.
            for offset in range(1, 6):
                if index + offset >= len(lines):
                    break
                candidate = lines[index + offset].strip()
                if not candidate or candidate.startswith(('*', '//', '/*')):
                    continue
                name = None
                objc = _OBJC_METHOD.match(candidate)
                if objc:
                    name = objc.group(1)
                else:
                    cxx = _CXX_DEFINITION.match(candidate)
                    if cxx:
                        name = cxx.group(1)
                if name:
                    found.setdefault(int(match.group(1), 16), name)
                break
    return found


def main(argv=None):
    """Emit the map, optionally rebased onto a running process."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path('Project'))
    parser.add_argument('--load', type=lambda v: int(v, 0),
                        help='the module load address, to emit absolute addresses')
    parser.add_argument('--lldb', action='store_true',
                        help='emit a sourceable lldb file of breakpoint aliases')
    arguments = parser.parse_args(argv)

    found = symbols(arguments.root)
    if not found:
        print('no annotated definitions found', file=sys.stderr)
        return 1

    if arguments.lldb and arguments.load is None:
        print('--lldb needs --load', file=sys.stderr)
        return 2

    if arguments.lldb:
        print('# Generated by tools/gen_symbol_map.py. The load address is baked in, so this file is')
        print('# only valid for the process it was generated against; regenerate after a relaunch.')
        for address, name in sorted(found.items()):
            # An alias name is a single command word: colons and tildes are not allowed in one.
            alias = name.replace('::', '_').replace('~', 'dtor_')
            print(f'command alias bp_{alias} breakpoint set -a {arguments.load + address:#x}')
        return 0

    for address, name in sorted(found.items()):
        if arguments.load is None:
            print(f'{address:#010x}  {name}')
        else:
            print(f'{arguments.load + address:#x}  {address:#010x}  {name}')
    print(f'\n{len(found)} symbols', file=sys.stderr)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
